# Configuration for request-info - https://github.com/behaviorbot/request-info

# *OPTIONAL* Comment to reply with
# Can be either a string :
requestInfoReplyComment: >
  Hey there! You didn't give us a whole lot of info about this issue/PR. We would love if you could provide more details. Please refer the 
  [contribution guide](https://github.com/CheshtaK/bookface/blob/master/.github/CONTRIBUTING.md) for PRs and 
  [issue guide](https://github.com/CheshtaK/bookface/tree/master/.github/ISSUE_TEMPLATE) for issues.


# *OPTIONAL* Label to be added to Issues and Pull Requests with insufficient information given
requestInfoLabelToAdd: needs-more-info

# *OPTIONAL* Require Issues to contain more information than what is provided in the issue templates
# Will fail if the issue's body is equal to a provided template
checkIssueTemplate: true

# *OPTIONAL* Require Pull Requests to contain more information than what is provided in the PR template
# Will fail if the pull request's body is equal to the provided template
checkPullRequestTemplate: true

# *OPTIONAL* Add a list of people whose Issues/PRs will not be commented on
# keys must be GitHub usernames
requestInfoUserstoExclude:
  - CheshtaK
